site_name: IRP Next v2
site_description: Documentation for IRP Next v2

theme:
  name: material
  palette:
    # Dark mode (default)
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - content.code.copy

plugins:
  - search
  - glightbox

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - stylesheets/extra.css
